### ISSUE TITLE
Ds4windows Lightbar color disappearing/ not showing 

### ISSUE THREAD

**Issue by jra22387** [jdanders/DS4JoyConWindows#1]
I have noticed a weird issue where once I connect to Bluetooth the lightbar just completely turns off even tho the controller still functions fine.  Is there a reason why the light doesn’t properly change with the profile color as you select?  I’ve reinstalled all drivers and removed the devices and seemed to work for a short bit but once I rebooted it was back to the same problem.  Again controller works but not light at all once connected.   Any ideas ?

**Comment by jdanders** [comment]
You would need to move this issue to https://github.com/Ryochan7/DS4Windows
